[package]
name = "rust-telnetd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
libc = "0.2.141"
num-derive = "0.3.3"
num-traits = "0.2.15"
subprocess = "0.2.9"
which = "4.4.0"
